import { Hono } from "hono"
import { cors } from "hono/cors"
import { type z } from "zod"
import { serve } from "@hono/node-server"
import { getUserIdByName } from "grafbase/db/user"
import { getTopic } from "grafbase/db/topic"
import * as edgedb from "edgedb"

export const app = new Hono()
export const client = edgedb.createClient()

app.onError((err, ctx) => {
  if ("format" in err) {
    console.error(JSON.stringify((err as z.ZodError).format(), undefined, 2))
  } else {
    console.error(err)
  }
  return ctx.json({ error: "Internal Server Error" }, 500)
})

app.use("*", cors())

app.get("/topics", async (ctx) => {
  // const userId = await getUserIdByName("Nikita")
  // const res = await getTopic("Physics", userId)
  // console.log(res)
  return ctx.json({
    name: "Physics",
    content: `# Physics

    [This](https://www.susanrigetti.com/physics) & [this Reddit thread](https://www.reddit.com/r/AskPhysics/comments/sxrg4q/how_can_i_learn_physics_on_my_own/) are nice places to start learning physics. I like reading [AskPhysics subreddit](https://www.reddit.com/r/AskPhysics/).

    [Arvin Ash](https://www.youtube.com/@ArvinAsh/videos), [PBS Space Time](https://www.youtube.com/@pbsspacetime/videos), [Unzicker's Real Physics](https://www.youtube.com/@TheMachian/videos) ([need to double check his content](https://www.math.columbia.edu/~woit/wordpress/?p=6156)) & [Ten Minute Physics](https://matthias-research.github.io/pages/tenMinutePhysics/index.html) are interesting.

    I found studying [Roger Penrose](https://en.wikipedia.org/wiki/Roger_Penrose)'s work mind opening.

    It's wild [how far humans got](https://www.youtube.com/watch?v=PHiyQID7SBs) to understanding physics and especially [quantum physics](quantum-physics/quantum-physics.md).

    Love [Sean Carroll](https://twitter.com/seanmcarroll)'s [book](https://www.preposterousuniverse.com/biggestideas/) and [podcast](https://www.preposterousuniverse.com/podcast/). [Mindscape AMA is great](https://docs.google.com/spreadsheets/d/1i2tmn7L-nlqOz0i-O1MVoOg6kafe9gC45VkaXs0LxMA/edit).

    ## Notes

    - What is energy?
      - There's no satisfying definition beyond "the quantity that is conserved over time." This may sound arbitrary and ad hoc but it emerges from this deep mathematical principal called Noether's theorem that states that for each symmetry (in this case, staying the same while moving forward or backwards in time), there is something that is conserved. In this context, momentum is the thing that is conserved over distance, and angular momentum is the thing that is conserved through rotations.
      - The less rigorous explanation is that it's essentially the currency used by physical systems to undergo change.
    - [One of the things you learn in Physics is that nothing is ever still or completely solid. All atoms vibrate and most(95+%) of their space is empty, where electrons spin. So everything you see is a vibrating mesh of molecules. Neutrinos are so small they can fly straight through everything, even planets! The only time anything stays completely still is at zero degrees Kelvin and it is theorized that time actually stands still at the this temperature.](https://www.reddit.com/r/shrooms/comments/c7i8ee/it_going_to_be_a_good_day/)
    - Emergent complexity: complexity arising from simple rules is interesting. One example of it is [cellular automata](https://natureofcode.com/book/chapter-7-cellular-automata/) and [Conway's game of life](https://en.wikipedia.org/wiki/Conway's_Game_of_Life).
    - [Gravity travels at the speed of light.](https://twitter.com/InertialObservr/status/1270499784546107393)
    - [Acceleration is independent of mass of object.](https://www.reddit.com/r/Physics/comments/iezeqe/gravity/)
    - [Inertia is an intrinsic property and can basically be described as a body’s resistance to acceleration/ change in it’s speed (1st law). What’s intertwined is inertia and force (not acceleration necessarily) since inertia (be it linear or rotational) of a particle would decide how much force is required to produce a certain acceleration (2nd law)](https://www.reddit.com/r/Physics/comments/iezeqe/gravity/)
    - [The future is probability, the past is information, the passage of time is the collapse of one state to the other.](https://www.reddit.com/r/AskPhysics/comments/mk5uo5/what_is_something_you_realized_about_our_universe/)
    - [Because atoms are actually 99.9999% (something similar to the degree) space, everything is also 99.9999% space but things cant pass through each other.](https://www.reddit.com/r/AskPhysics/comments/mk5uo5/what_is_something_you_realized_about_our_universe/)
    - [All matter has kinetic and potential energy. It is easier to think of it as those are the only types of energy.](https://www.reddit.com/r/NoStupidQuestions/comments/nedp7p/if_you_cant_create_or_destroy_energy_then_where/)
    - [Energy can change forms. From heat to potential to kinetic to radiation to heat.](https://www.reddit.com/r/NoStupidQuestions/comments/nedp7p/if_you_cant_create_or_destroy_energy_then_where/)
    - [Gravity propagates at the speed of light.](https://www.reddit.com/r/AskPhysics/comments/s5lcwq/is_gravity_faster_than_light/)

    ## Links

    - [So You Want To Learn Physics...](https://www.susanrigetti.com/physics) ([HN](https://news.ycombinator.com/item?id=24088985))
    - [The Astonishing Simplicity of Everything](https://www.youtube.com/watch?v=f1x9lgX8GaE)
    - [The Map of Physics](https://www.youtube.com/watch?v=ZihywtixUYo)
    - [The Theoretical Minimum Courses](https://theoreticalminimum.com/courses) - Theoretical Physics Education.
    - [Fun to Imagine](https://www.youtube.com/watch?v=eqtuNXWT0mo)
    - [Stephen Hawking had pinned his hopes on 'M-theory' to fully explain the universe—here's what it is](https://phys.org/news/2018-03-stephen-hawking-pinned-m-theory-fully.html)
    - [Ask HN: How to self-learn electronics?](https://news.ycombinator.com/item?id=16775744)
    - [Conceptual illustration of time and space distortion near a mass](https://gfycat.com/AliveIndelibleElkhound)
    - [Amazing Sand Pendulum](https://www.youtube.com/watch?v=kesRiQbm9V0)
    - [Small physics lectures](https://www.youtube.com/playlist?list=PLF71B362214423F9D)
    - [What in physics is fundamental?](https://www.reddit.com/r/askscience/comments/7cnx2u/what_in_physics_is_fundamental/)
    - [The World in UV](https://www.youtube.com/watch?v=V9K6gjR07Po)
    - [Why does it take a million years for a photon moving at the speed of light to reach the sun's surface from its core?](https://www.reddit.com/r/askscience/comments/5q79dy/why_does_it_take_a_million_years_for_a_photon/dcwyis0/)
    - [Why do I study Physics? (2013)](https://www.youtube.com/watch?v=pom8S7qF5Gk)
    - [Is Matter Conscious? (2017)](http://nautil.us/issue/47/consciousness/is-matter-conscious) ([HN](https://news.ycombinator.com/item?id=19240742))
    - [The Mystery at the Bottom of Physics (2019)](https://www.youtube.com/watch?v=EH-z9gE2uGY)
    - [Ask HN: Physicists of HN, what are you working on these days? (2019)](https://news.ycombinator.com/item?id=19500151)
    - [In conversation with Nima Arkani-Hamed (2014)](https://www.youtube.com/watch?v=pup3s86oJXU)
    - [A Peek into Einstein's Zurich Notebook](https://www.pitt.edu/%7Ejdnorton/Goodies/Zurich_Notebook/)
    - [David Tong: Lectures on Theoretical Physics](http://www.damtp.cam.ac.uk/user/tong/teaching.html)
    - [Mathematics for Physics: Crash Course](https://sites.uci.edu/inertialobserver/mathematics-for-physics-crash-course/)
    - [What are some of the "cornerstone books" in physics? (2019)](https://www.reddit.com/r/Physics/comments/ebf5bn/what_are_some_of_the_cornerstone_books_in_physics/)
    - [The Feyman Lectures on Physics](https://www.feynmanlectures.caltech.edu/)
    - [Principles of Optics](https://cds.cern.ch/record/396122/files/0521642221_TOC.pdf) - Electromagnetic theory of propagation, interference and diffraction of light.
    - [What Makes the Hardest Equations in Physics So Difficult? (2019)](https://www.quantamagazine.org/what-makes-the-hardest-equations-in-physics-so-difficult-20180116/)
    - [What are the minimum number of empirical observations/laws necessary to recover modern physics? (2020)](https://www.reddit.com/r/Physics/comments/ekerj7/what_are_the_minimum_number_of_empirical/)
    - [Physics Travel Guide](https://physicstravelguide.com/) - Expository wiki which explains concepts in three levels of difficulty. We call these levels: intuitive, concrete and abstract. ([HN](https://news.ycombinator.com/item?id=22757466))
    - [What is an area of physic that is grossly underrepresented? (2020)](https://www.reddit.com/r/Physics/comments/em8oqd/what_is_an_area_of_physic_that_is_grossly/)
    - [Why the foundations of physics have not progressed for 40 years (2020)](https://iai.tv/articles/why-physics-has-made-no-progress-in-50-years-auid-1292) ([HN](https://news.ycombinator.com/item?id=22033864))
    - [Noether’s Theorem - A Quick Explanation (2019)](https://quantum-friend-theory.tumblr.com/post/172814384897/noethers-theorem-a-quick-explanation) ([HN](https://news.ycombinator.com/item?id=22033012))
    - [Paul Dirac Interview, Göttingen 1982](https://www.youtube.com/watch?v=Et8-gg6XNDY)
    - [Resources for the Physics Olympiad](https://www.reddit.com/r/Physics_olympiad/wiki/index)
    - [Snow Crystals (2019)](https://arxiv.org/abs/1910.06389)
    - [Gears (2020)](https://ciechanow.ski/gears/) ([HN](https://news.ycombinator.com/item?id=22310813))
    - [The Church-Turing Thesis and Physics (2019)](https://video.ethz.ch/speakers/bernays/2019/7b11b50e-f813-4d26-95e0-616cc350708c.html)
    - [Einstein Papers Project](https://www.einstein.caltech.edu/) - Provides the first complete picture of Einstein’s massive written legacy.
    - [Intuitive and visual guide to understanding Maxwell's equations](https://github.com/photonlines/Intuitive-Guide-to-Maxwells-Equations/blob/master/PDF/An%20Intuitive%20Guide%20to%20Maxwell%27s%20Equations.pdf) ([HN](https://news.ycombinator.com/item?id=23700295))
    - [HEPML Resources](https://github.com/iml-wg/HEP-ML-Resources) - Listing of useful learning resources for machine learning applications in high energy physics (HEPML).
    - [Explorable Physics](https://landgreen.github.io/physics/index.html) - Course notes for algebra based physics with explorable explanations. ([Code](https://github.com/landgreen/physics))
    - [Ask HN: How to Self Study Physics? (2020)](https://news.ycombinator.com/item?id=22682837)
    - [Information Is Physics](https://cacm.acm.org/magazines/2019/11/240356-information-is-physics/fulltext) ([HN](https://news.ycombinator.com/item?id=21665931))
    - [Dr. Neil Turok - "From zero to infinity, and beyond!" (2012)](https://www.youtube.com/watch?v=URYOkgbr604)
    - [Sir Roger Penrose - Plotting the Twist of Einstein’s Legacy (2020)](https://overcast.fm/+TYXKbJ8js)
    - [Roger Penrose | Interview | Gravity, Hawking Points and Twistor Theory (2019)](https://www.youtube.com/watch?v=9Gl8pwY2kW8)
    - [Why is Maxwell’s Theory so hard to understand? (2007)](https://www.damtp.cam.ac.uk/user/tong/em/dyson.pdf) ([HN](https://news.ycombinator.com/item?id=22810867))
    - [How to learn quantum mechanics on your own (2019)](https://lookingglassuniver.wixsite.com/blog/post/how-to-learn-quantum-mechanics-on-your-own) ([Video](https://www.youtube.com/watch?v=Rs572Cf4zkk))
    - [Shining a Flashlight on Digital Holography (2020)](https://blog.lookingglassfactory.com/process/shining-a-flashlight-on-digital-holography/) ([HN](https://news.ycombinator.com/item?id=22832627))
    - [HN: Scientists use the Tokyo Skytree to test general relativity (2020)](https://news.ycombinator.com/item?id=22831715)
    - [The Biggest Ideas in the Universe (2020)](https://www.youtube.com/playlist?list=PLrxfgDEc2NxZJcWcrxH3jyjUUrJlnoyzX)
    - [Essays by Jakob Schwichtenberg](http://jakobschwichtenberg.com/archive/)
    - [Physics From Symmetry book (2015)](http://physicsfromsymmetry.com/)
    - [No-Nonsense Books on Physics](https://nononsensebooks.com/)
    - [The Wolfram Physics Project (2020)](https://www.wolframphysics.org/) ([HN](https://news.ycombinator.com/item?id=22866284)) ([Video](https://www.youtube.com/watch?v=rbfFt2uNEyQ)) ([Article](https://writings.stephenwolfram.com/2020/04/finally-we-may-have-a-path-to-the-fundamental-theory-of-physics-and-its-beautiful/)) ([Code](https://github.com/maxitg/SetReplace))
    - [The Wolfram Physics Project: The First Two Weeks (2020)](https://writings.stephenwolfram.com/2020/04/the-wolfram-physics-project-the-first-two-weeks/#what-about-peer-review-and-all-that)
    - [Why Stephen Wolfram’s research program is a dead end (2020)](https://www.singlelunch.com/2020/04/23/why-stephen-wolframs-research-program-is-a-dead-end/) ([Reddit](https://www.reddit.com/r/math/comments/g6qg0k/why_stephen_wolframs_research_program_is_a_dead/))
    - [A Class of Models with the Potential to Represent Fundamental Physics](https://www.wolframphysics.org/technical-introduction/) ([Twitter](https://twitter.com/cmuratori/status/1250116047585210369))
    - [Why is the speed of light a constant?](https://www.reddit.com/r/AskPhysics/comments/g1fx1l/why_is_the_speed_of_light_a_constant/)
    - [The Meaning of Einstein's Equation](http://math.ucr.edu/home/baez/einstein/)
    - [John Baez’s research/blog](http://math.ucr.edu/home/baez/)
    - [Why is light slower in glass? - Sixty Symbols (2013)](https://www.youtube.com/watch?v=CiHN0ZWE5bk)
    - [Quantum Fields: The Real Building Blocks of the Universe - David Tong (2017)](https://www.youtube.com/watch?v=zNVQfWC_evg)
    - [David Tong's research papers](https://arxiv.org/a/tong_d_1.html)
    - [Are quantum fields in any way similar to classical fields? (2020)](https://www.reddit.com/r/askscience/comments/fo4igl/are_quantum_fields_in_any_way_similar_to/)
    - [QED: The Strange Theory of Light and Matter (2020)](https://medium.com/cantors-paradise/qed-the-strange-theory-of-light-and-matter-df50782b1651) ([Reddit](https://www.reddit.com/r/Physics/comments/gc3mp8/qed_the_strange_theory_of_light_and_matter/))
    - [SIGGRAPH 2020 Technical Paper: N-Dimensional Rigid Body Dynamics](https://marctenbosch.com/news/2020/05/siggraph-2020-technical-paper-n-dimensional-rigid-body-dynamics/) ([HN](https://news.ycombinator.com/item?id=23112312))
    - [A Mathematical Theory of Communication - Claude Shannon (1948)](http://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf)
    - [Brief introduction to the beauty of Information Theory (2020)](https://notamonadtutorial.com/a-brief-introduction-to-the-beauty-of-information-theory-8357f5b6a355)
    - [Finding new physics will require a new particle collider (2020)](https://www.economist.com/science-and-technology/2020/01/02/finding-new-physics-will-require-a-new-particle-collider) ([HN](https://news.ycombinator.com/item?id=23131526))
    - [Structure and Interpretation of Classical Mechanics](https://mitpress.mit.edu/sites/default/files/titles/content/sicm_edition_2/book.html) ([HN](https://news.ycombinator.com/item?id=23153778)) ([Code](https://github.com/hnarayanan/sicm)) ([Web](https://groups.csail.mit.edu/mac/users/gjs/6946/sicm-html/)) ([Exercises and notes](https://github.com/sicmutils/sicm-exercises))
    - [Evidence for Anyons, a Third Kingdom of Particles (2020)](https://www.quantamagazine.org/milestone-evidence-for-anyons-a-third-kingdom-of-particles-20200512/) ([HN](https://news.ycombinator.com/item?id=23161959))
    - [DIY Particle Detector](https://github.com/ozel/DIY_particle_detector) - Mobile low-cost spectrometer for measuring radioactivity and the energy of ionising radiation like alpha particles and electrons. ([HN](https://news.ycombinator.com/item?id=23196177))
    - [Speed of light is the speed limit relative to what? (2020)](https://www.reddit.com/r/AskPhysics/comments/gkps4a/speed_of_light_is_the_speed_limit_relative_to_what/)
    - [We have yet to experimentally confirm that the electric potential is physical (2020)](https://www.reddit.com/r/Physics/comments/gl15nb/we_have_yet_to_experimentally_confirm_that_the/)
    - [Leonard Susskind lecture series](https://www.youtube.com/playlist?list=PLa1wke5CmQTSmrkhJwlzH5uzRd4fRLOiz)
    - [What happens when photons collide? (2020)](https://www.reddit.com/r/askscience/comments/gshi9g/what_happens_when_photons_collide/)
    - [Mapping the Multiverse (2020)](https://www.youtube.com/watch?v=4v9A9hQUcBQ)
    - [Photonic Crystals: Periodic Surprises in Electromagnetism](http://ab-initio.mit.edu/photons/tutorial/)
    - [MIT Mathematical Methods in Nanophotonics course notes](https://github.com/mitmath/18369)
    - [Where in an atom exactly is a nucleus located? Is it in the centre or does its location vary from time to time? (2020)](https://www.reddit.com/r/askscience/comments/gyc73r/where_in_an_atom_exactly_is_a_nucleus_located_is/)
    - [Ask HN: Without Einstein, would General Relativity be discovered by now? (2020)](https://news.ycombinator.com/item?id=23450827)
    - [If breaking the sound barrier causes a sonic boom, what would breaking the light speed barrier do? (2020)](https://www.reddit.com/r/askscience/comments/gz1u71/if_breaking_the_sound_barrier_causes_a_sonic_boom/)
    - [If you were starting your physics PhD right now, what would you study? (2020)](https://www.reddit.com/r/Physics/comments/h92nhn/if_you_were_starting_your_physics_phd_right_now/)
    - [Some Frequently Asked Questions About Virtual Particles](http://math.ucr.edu/home/baez/physics/Quantum/virtual_particles.html)
    - [Applied Dynamical Systems (2020)](https://www.youtube.com/playlist?list=PL8erL0pXF3JZqdlYIfTTyibOqSqwzRdVV)
    - [What are some common misconceptions in physics? (2020)](https://www.reddit.com/r/AskPhysics/comments/haaw4h/what_are_some_common_misconceptions_in_physics/)
    - [Papers by Edward Witten](https://arxiv.org/search/hep-th?searchtype=author&query=Witten%2C+E)
    - [Feynman Lectures on the Strong Interactions (2020)](https://www.math.columbia.edu/~woit/wordpress/?p=11782) ([HN](https://news.ycombinator.com/item?id=23535868))
    - [What are good online resources for learning physics? (2020)](https://www.reddit.com/r/AskPhysics/comments/he6uq0/what_are_good_online_resources_for_learning/)
    - [What is a photon? (2017)](http://blog.sigfpe.com/2017/08/what-is-photon.html) ([HN](https://news.ycombinator.com/item?id=23637576))
    - [Do gravitational waves destructively interfere with each other? (2020)](https://www.reddit.com/r/AskPhysics/comments/hf7rxe/do_gravitational_waves_destructively_interfere/)
    - [The physics behind spring animations (2020)](https://blog.maximeheckel.com/posts/the-physics-behind-spring-animations)
    - [The Idea of Entropy Has Led Us Astray (2020)](http://nautil.us/issue/86/energy/the-idea-of-entropy-has-led-us-astray) ([HN](https://news.ycombinator.com/item?id=23711872))
    - [Do we need a Theory of Everything? (2020)](http://backreaction.blogspot.com/2020/07/do-we-need-theory-of-everything.html) ([HN](https://news.ycombinator.com/item?id=23815824))
    - [Video Demonstrations in Lasers and Optics (2008)](https://ocw.mit.edu/resources/res-6-006-video-demonstrations-in-lasers-and-optics-spring-2008/index.htm)
    - [Two-beam Interference — Collimated Beams](https://ocw.mit.edu/resources/res-6-006-video-demonstrations-in-lasers-and-optics-spring-2008/demonstrations-in-physical-optics/two-beam-interference-2014-collimated-beams/)
    - [NANOGrav](http://nanograv.org/) - North American Nanohertz Observatory for Gravitational Waves. ([Tweet](https://twitter.com/coreyspowell/status/1292288928922427393))
    - [Algorithmic Theories of Everything (2000)](https://arxiv.org/abs/quant-ph/0011122) ([HN](https://news.ycombinator.com/item?id=24093599))
    - [Periodic table, color coded by the likely origin of each element](https://twitter.com/olivertlord/status/1292562140776271872) ([HN](https://news.ycombinator.com/item?id=24107656))
    - [Twistors and the Standard Model (2020)](https://www.math.columbia.edu/~woit/wordpress/?p=11899)
    - [Spacetime has 3 space dimensions and 1 time dimension. Why?](https://twitter.com/johncarlosbaez/status/1294317943359016960)
    - [A flutter in time: Quantum mechanics is immune to the butterfly effect (2020)](https://www.economist.com/science-and-technology/2020/08/15/quantum-mechanics-is-immune-to-the-butterfly-effect) ([HN](https://news.ycombinator.com/item?id=24167691))
    - [A brief introduction to observational entropy (2020)](https://arxiv.org/abs/2008.04409)
    - [Humanly Traversable Wormholes (2020)](https://arxiv.org/abs/2008.06618) ([HN](https://news.ycombinator.com/item?id=24196052))
    - [Stephen Wolfram & Eric Weinstein: The Nature of Mathematical Reality (2020)](https://overcast.fm/+Hf52xFKgY)
    - [Symmetry Magazine](https://www.symmetrymagazine.org/) - Dimensions of particle physics.
    - [A Candidate Geometrical Formalism for the Foundations of Mathematics and Physics (2020)](https://www.wolframphysics.org/bulletins/2020/08/a-candidate-geometrical-formalism-for-the-foundations-of-mathematics-and-physics/)
    - [Mathematics for Physics](https://www.mathphysicsbook.com/) - Illustrated Handbook.
    - [Elements of Physics](https://elements-of-physics.surge.sh/) - Interactive simulation which describes different elements of physics like Gravity, Acceleration and Force.
    - [Do we really travel through time with the speed of light? (2020)](https://backreaction.blogspot.com/2020/08/do-we-really-travel-through-time-with.html) ([HN](https://news.ycombinator.com/item?id=24328617))
    - [Physics is stuck (2020)](https://www.salon.com/2020/09/06/physics-is-stuck--and-needs-another-einstein-to-revolutionize-it-physicist-avi-loeb-says/) ([HN](https://news.ycombinator.com/item?id=24454438))
    - [Manifestations of waves in nature (2020)](https://twitter.com/QiaochuYuan/status/1306048749462908931)
    - [Daniel and Jorge Explain the Universe - Most Common Listener Questions (2020)](https://overcast.fm/+Oq0a0jjIo)
    - [I am self-studying physics, which book should I get? (2020)](https://www.reddit.com/r/AskPhysics/comments/iwae2d/i_am_selfstudying_physics_which_book_should_i_get/)
    - [A Child’s Guide to Spinors (2016)](http://www.weylmann.com/spinor.pdf)
    - [NIST Pair of Atomic Clocks Reveal Einstein's Relativity at a Personal Scale (2010)](https://www.nist.gov/news-events/news/2010/09/nist-pair-aluminum-atomic-clocks-reveal-einsteins-relativity-personal-scale) ([HN](https://news.ycombinator.com/item?id=24634461))
    - [The Grand Design by Stephen Hawking](https://blas.com/the-grand-design/)
    - [Moonshot Papers (2020)](https://davidwyde.com/thoughts/moonshot-papers/)
    - [The Nobel Prize in Physics 2020](https://www.nobelprize.org/prizes/physics/2020/press-release/) ([HN](https://news.ycombinator.com/item?id=24696230))
    - [The Superpowers of Super-Thin Materials (2020)](https://www.nytimes.com/2020/01/07/science/physics-materials-electronics.html) ([HN](https://news.ycombinator.com/item?id=24714994))
    - [How Andrea Ghez won the Nobel for an experiment nobody thought would work (2020)](https://www.scientificamerican.com/article/how-andrea-ghez-won-the-nobel-for-an-experiment-nobody-thought-would-work/) ([HN](https://news.ycombinator.com/item?id=24740475))
    - [Scientists find upper limit for the speed of sound (2020)](https://phys.org/news/2020-10-scientists-upper-limit.html) ([HN](https://news.ycombinator.com/item?id=24736738))
    - [Room-Temperature Superconductivity Achieved for the First Time (2020)](https://www.quantamagazine.org/physicists-discover-first-room-temperature-superconductor-20201014/) ([HN](https://news.ycombinator.com/item?id=24777268))
    - [Cantera](https://github.com/Cantera/cantera) - Chemical kinetics, thermodynamics, and transport tool suite. ([Web](https://cantera.org/)) ([Jupyter Examples](https://github.com/Cantera/cantera-jupyter))
    - [Q&A with 2020 Nobel laureate Roger Penrose (2020)](https://www.youtube.com/watch?v=fQPUYjoG5jI)
    - [What is relativity, anyway? (2020)](https://maxhodak.com/nonfiction/2020/09/18/relativity.html)
    - [Spacetime Physics book (1992)](http://www.eftaylor.com/spacetimephysics/) - By Taylor and Wheeler (Feynman's PhD advisor).
    - [Gravity is not a force – free-fall parabolas are straight lines in spacetime](https://timhutton.github.io/GravityIsNotAForce/) ([HN](https://news.ycombinator.com/item?id=24821141)) ([Code](https://github.com/timhutton/GravityIsNotAForce))
    - [HyperPhysics](http://hyperphysics.phy-astr.gsu.edu/hbase/index.html) - Physics Exploration Environment.
    - [A new way to visualize General Relativity (2020)](https://www.youtube.com/watch?v=wrwgIjBUYVc)
    - [Space Itself Is Expanding: Gravity and General Relativity Explained (2015)](https://medium.com/@davidlevitt/space-itself-is-expanding-gravity-and-general-relativity-explained-6395aa2e4d69)
    - [The female mathematician who changed the course of physics—but couldn’t get a job (2015)](https://arstechnica.com/science/2015/05/the-female-mathematician-who-changed-the-course-of-physics-but-couldnt-get-a-job/)
    - [Theoretical Physics Reference](https://www.theoretical-physics.com/dev/index.html) - Open source theoretical physics book. ([Web](https://www.theoretical-physics.com/)) ([Code](https://github.com/certik/theoretical-physics))
    - [A New Map of the Standard Model of Particle Physics (2020)](https://www.quantamagazine.org/a-new-map-of-the-standard-model-of-particle-physics-20201022/) ([HN](https://news.ycombinator.com/item?id=24877612)) ([HN](https://news.ycombinator.com/item?id=31055798))
    - [What is Energy? Is Energy conserved? (2020)](https://www.youtube.com/watch?v=ZYM6HMLgIKA)
    - [Why no one has measured the speed of light (2020)](https://www.youtube.com/watch?v=pTn6Ewhb27k)
    - [How to Become a Good Theoretical Physicist](https://www.goodtheorist.science/) ([HN](https://news.ycombinator.com/item?id=33306707))
    - [Advance Electromagnetism Notes](https://andrealommen.github.io/PHY309/lectures)
    - [Penrose diagrams](https://jila.colorado.edu/~ajsh/insidebh/penrose.html)
    - [What Is a Particle? (2020)](https://www.quantamagazine.org/what-is-a-particle-20201112/) ([HN](https://news.ycombinator.com/item?id=25085286))
    - [A Spacetime Surprise: Time Isn’t Just Another Dimension (2020)](https://www.forbes.com/sites/startswithabang/2020/08/12/a-spacetime-surprise-time-isnt-just-another-dimension/) ([HN](https://news.ycombinator.com/item?id=25109046))
    - [How Radiation Looks Like](https://twitter.com/isaboemeke/status/1328037931521437696)
    - [Visual demonstration of the power of sound to create order out of chaos](https://twitter.com/tedgioia/status/1327511170190864384)
    - [I’m a pure mathematician who knows no physics. What should I read?](https://twitter.com/algeom/status/1335642248797536256)
    - [2020 Nobel Lectures in Physics](https://www.youtube.com/watch?v=DWF1uNb9Q1Q)
    - [Crystallography](https://www.xtal.iqfr.csic.es/Cristalografia/index-en.html)
    - [Peter Woit's Research](https://www.math.columbia.edu/~woit/)
    - [Why The Speed Of Light Can't Be Measured (2020)](https://www.youtube.com/watch?v=pTn6Ewhb27k)
    - [One-way speed of light](https://en.wikipedia.org/wiki/One-way_speed_of_light)
    - [Well, Actually – Physics Answers](http://backreaction.blogspot.com/2020/12/well-actually-10-physics-answers.html) ([HN](https://news.ycombinator.com/item?id=25588888))
    - [Heat Capacity and the Speed of Sound (2020)](https://www.daniellowengrub.com/blog/2020/12/19/heat-capacity-sound)
    - [Britney Spears' Guide to Semiconductor Physics](http://britneyspears.ac/lasers.htm) ([HN](https://news.ycombinator.com/item?id=25626532))
    - [PhysURLs](https://physurls.com/) - Physics news aggregator.
    - [The Physics Hub](https://physicshub.herokuapp.com/) - One place to view all the simulations in physics.
    - [Quanta Magazine: Physics](https://www.quantamagazine.org/physics/)
    - [ParticleBites](https://www.particlebites.com/) - High energy physics reader's digest.
    - [Why is light always moving?](https://www.reddit.com/r/explainlikeimfive/comments/l0q82z/eli5_what_propels_light_why_is_light_always_moving/)
    - [Max Planck Institute for Solid State Research](https://www.fkf.mpg.de/en)
    - [What does "Entropy" mean? (2021)](https://www.reddit.com/r/askscience/comments/l6g1nb/what_does_entropy_mean/)
    - [What makes a physicist, a great physicist? (2021)](https://www.reddit.com/r/Physics/comments/l9dqnp/what_makes_a_physicist_a_great_physicist/)
    - [Galaxy-Size Gravitational-Wave Detector Hints at Exotic Physics (2021)](https://www.scientificamerican.com/article/galaxy-size-gravitational-wave-detector-hints-at-exotic-physics/) ([HN](https://news.ycombinator.com/item?id=26037041))
    - [Reforming the Mathematical Language of Physics (2002)](http://worrydream.com/refs/Hestenes-ReformingTheMathematicalLanguageOfPhysics.pdf)
    - [Sean Carroll's AMA (2021)](https://overcast.fm/+S_7njW_Sw)
    - [Other than particles and waves, are there any other fundamental descriptors? (2021)](https://www.reddit.com/r/AskPhysics/comments/lmuuty/other_than_particles_and_waves_are_there_any/)
    - [EinsteinPy Project](https://einsteinpy.org/) - Python package dedicated to problems arising in General Relativity and gravitational physics. ([Code](https://github.com/einsteinpy/einsteinpy)) ([GitHub](https://github.com/einsteinpy))
    - [ScienceClic English - YouTube](https://www.youtube.com/c/ScienceClicEN/videos)
    - [List of Unsolved Problems in Physics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_physics)
    - [Maps of Matter (2021)](https://futureofmatter.com/maps_of_matter.html) ([HN](https://news.ycombinator.com/item?id=27673753))
    - [The Future of Matter](https://futureofmatter.com/) - Notes on the striking things we're learning to do with matter.
    - [What do photons have to do with the electromagnetic force? (2021)](https://www.reddit.com/r/AskPhysics/comments/lxzs4x/what_do_photons_have_to_do_with_the/)
    - [Problems with Eric Weinstein's “Geometric Unity” (2021)](http://backreaction.blogspot.com/2021/03/guest-post-problems-with-eric.html) ([HN](https://news.ycombinator.com/item?id=26371052))
    - [Computation in Physical Systems](https://plato.stanford.edu/entries/computation-physicalsystems/)
    - [Virtual Particles: What are they? (2011)](https://profmattstrassler.com/articles-and-posts/particle-physics-basics/virtual-particles-what-are-they/) ([HN](https://news.ycombinator.com/item?id=26368637))
    - [Why Lagrangian Mechanics is Better than Newtonian Mechanics F=ma | Euler-Lagrange Equation (2021)](https://www.youtube.com/watch?v=KpLno70oYHE)
    - [Incoherent light sources (like a lightbulb) can actually be coherent at very small timescales](https://twitter.com/bencbartlett/status/1369396941730312193)
    - [Poster summarizing the standard model of particle physics (2021)](https://twitter.com/DominicWalliman/status/1370044170274938886)
    - [Alternative interpretations of classical physics (2019)](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.100.062107) ([HN](https://news.ycombinator.com/item?id=26552942))
    - [How does Hawking Radiation work? (2021)](https://www.youtube.com/watch?v=rrUvLlrvgxQ)
    - [The Secret of Synchronization (2021)](https://www.youtube.com/watch?v=t-_VPRCtiUg)
    - [When Feynman Met Dirac](https://www.cantorsparadise.com/when-feynman-met-dirac-fe9cca0006df) ([HN](https://news.ycombinator.com/item?id=26697227))
    - [The Koide Formula (2021)](https://johncarlosbaez.wordpress.com/2021/04/04/the-koide-formula/)
    - [Leonard Susskind on Richard Feynman, the Holographic Principle, and Unanswered Questions in Physics (2018)](https://www.youtube.com/watch?v=CQAcLW6qdQY)
    - [Muon G-2 Experiment at Fermilab Finds Hint of New Particles (2021)](https://www.quantamagazine.org/muon-g-2-experiment-at-fermilab-finds-hint-of-new-particles-20210407/) ([HN](https://news.ycombinator.com/item?id=26738989)) ([HN 2](https://news.ycombinator.com/item?id=26726269))
    - [This result could change physics forever (2021)](https://www.youtube.com/watch?v=0roQUZvU-As)
    - [Who are the current "rock stars" in physics? (2021)](https://www.reddit.com/r/AskPhysics/comments/mnotsv/who_are_the_current_rock_stars_in_physics/)
    - [NEWS: What's up with Muons? - Sixty Symbols (2021)](https://www.youtube.com/watch?v=kBzn4o4z5Bk) ([Reddit](https://www.reddit.com/r/Physics/comments/mpjzp1/news_whats_up_with_muons_sixty_symbols/))
    - [Can We Understand the Standard Model Using Octonions?](http://pirsa.org/21040005/) ([Tweet](https://twitter.com/johncarlosbaez/status/1382358155389136899))
    - [The Wolfram Physics Project: A One-Year Update (2021)](https://writings.stephenwolfram.com/2021/04/the-wolfram-physics-project-a-one-year-update/) ([HN](https://news.ycombinator.com/item?id=26808991))
    - [Collection of Videos in Support of Geometric Unity](https://pullthatupjamie.com/) ([Reddit](https://www.reddit.com/r/ThePortal/comments/msypp9/does_anybody_have_a_good_eli5_for_geometric_unity/))
    - [David Tong: Lectures on Particle Physics](http://www.damtp.cam.ac.uk/user/tong/particle.html) ([Reddit](https://www.reddit.com/r/Physics/comments/mwzuem/david_tong_drops_a_new_set_of_lecture_notes_on/))
    - [The Map of Particle Physics | The Standard Model Explained (2021)](https://www.youtube.com/watch?v=mYcLuWHzfmE)
    - [Statistical mechanics from entanglement: The Eigenstate Thermalization Hypothesis (2021)](https://www.youtube.com/watch?v=p4fpzYD_WRU) ([Reddit](https://www.reddit.com/r/Physics/comments/n36b5f/statistical_mechanics_from_entanglement_the/))
    - [Are all forces illusions? (2020)](https://www.youtube.com/watch?v=YRgBLVI3suM)
    - [Intersection-free Rigid Body Dynamics (2021)](https://ipc-sim.github.io/rigid-ipc/)
    - [Gravity is a double copy of other forces (2021)](https://www.quantamagazine.org/how-gravity-is-a-double-copy-of-other-forces-20210504/) ([HN](https://news.ycombinator.com/item?id=27094179))
    - [Lectures on Geometrical Anatomy of Theoretical Physics](https://www.youtube.com/playlist?list=PLPH7f_7ZlzxTi6kS4vCmv4ZKm9u8g5yic)
    - [An incomplete introduction to modern computational methods in physics part 1: Diagonalization](https://www.youtube.com/watch?v=LtiiBkolFo8) ([Reddit](https://www.reddit.com/r/Physics/comments/ndovks/an_incomplete_introduction_to_modern/))
    - [What are the shortest, peer-reviewed articles in physics? (2021)](https://www.reddit.com/r/AskPhysics/comments/nhm3ya/what_are_the_shortest_peerreviewed_articles_in/)
    - [Coanda Effect (2017)](https://www.youtube.com/watch?v=NvzXKZNJ7ZU)
    - [The Feynman Lectures on Physics (1964)](https://feynmanlectures.caltech.edu/) ([HN](https://news.ycombinator.com/item?id=30792902))
    - [The Feynman Lectures on Physics Audio Collection](https://www.feynmanlectures.caltech.edu/flptapes.html) ([HN](https://news.ycombinator.com/item?id=27322636))
    - [Scattering Theory of Waves and Particles (1982)](https://link.springer.com/book/10.1007/978-3-642-88128-2)
    - [Physics-informed neural networks with hard constraints for inverse design (2021)](https://arxiv.org/abs/2102.04626) ([Code](https://github.com/lululxvi/hpinn))
    - [Of the physicists that are still 'alive,' what is the top 5 of physicists who has contributed more to our understanding of the universe? (2021)](https://www.reddit.com/r/AskPhysics/comments/npn7au/of_the_physicists_that_are_still_alive_what_is/)
    - [Simulation of photons refracting through a dispersive cylinder, by solution of the eikonal equation](https://twitter.com/jamportz/status/1399463006468198404)
    - [When did you realize you weren’t going to be an outstanding physicist. (2021)](https://www.reddit.com/r/Physics/comments/nqdhco/when_did_you_realize_you_werent_going_to_be_an/)
    - [Does gravity bend gravity?](https://physics.stackexchange.com/questions/643765/does-gravity-bend-gravity)
    - [Nanoscale and Quantum Photonics Lab](https://nqp.stanford.edu/)
    - [Are the number of atoms in the universe fixed? (2021)](https://www.reddit.com/r/AskPhysics/comments/oj92rg/are_the_number_of_atoms_in_the_universe_fixed/)
    - [The Quantum Theory of Fields Book (2013)](https://www.cambridge.org/core/books/quantum-theory-of-fields/22986119910BF6A2EFE42684801A3BDF)
    - [Steven Weinberg's books on QFT](https://drive.google.com/drive/u/0/folders/1pGI0QMCw4DVSUhL0mfeoPGN4CIC2wGAx) ([Reddit](https://www.reddit.com/r/Physics/comments/oqjqws/rip_steven_weinberg_19332021/))
    - [What is Quantum Field Theory, and What Did We Think It Is? (1997)](https://arxiv.org/abs/hep-th/9702027) ([Tweet](https://twitter.com/seanmcarroll/status/1418804903871356930))
    - [Steven Weinberg Has Died (2021)](https://twitter.com/johncarlosbaez/status/1418804320611364867) ([HN](https://news.ycombinator.com/item?id=27939083))
    - [Steven Weinberg (1933-2021): a personal view](https://www.scottaaronson.com/blog/?p=5566)
    - [Dreams of a Final Theory Book (1994)](https://www.goodreads.com/book/show/150129.Dreams_of_a_Final_Theory) ([Article](https://news.utexas.edu/2021/07/24/ut-austin-mourns-death-of-world-renowned-physicist-steven-weinberg/))
    - [Online Course: Machine Learning for Physicists 2020](https://pad.gwdg.de/s/HJtiTE__U) ([Code](https://github.com/FlorianMarquardt/machine-learning-for-physicists))
    - [An Analytical, Statistical Approximate Solution for Dissipative and non-Dissipative Binary-Single Stellar Encounters (2021)](https://arxiv.org/abs/2011.00010) ([HN](https://news.ycombinator.com/item?id=28178509)) ([HN](https://news.ycombinator.com/item?id=28241758))
    - [What is the Chandrasekhar Limit? (2021)](https://www.youtube.com/watch?v=oxYbShKkw-4)
    - [The Planck scale: Is there a fundamental limit to space and time? (2020)](https://www.youtube.com/watch?v=5kuRatz2rj0)
    - [Deriving Einstein's most famous equation: Why does energy = mass x speed of light squared? (2021)](https://www.youtube.com/watch?v=KZ8G4VKoSpQ)
    - [Moments of Discovery](https://history.aip.org/exhibits/mod/index.html) - Tells the story of three scientific discoveries in the scientists' own words.
    - [Relativity: A Modern Primer](http://ramp-book.com/) ([HN](https://news.ycombinator.com/item?id=28421209))
    - [Physics of Racing](https://www.youtube.com/watch?v=bYp2vvUgEqE)
    - [How strong would a magnetic field have to be to kill you?](https://gravityandlevity.wordpress.com/2015/01/12/how-strong-would-a-magnetic-field-have-to-be-to-kill-you/#comment-3929) ([HN](https://news.ycombinator.com/item?id=28463855))
    - [Physics ∩ ML](http://physicsmeetsml.org/) - Virtual hub at the interface of theoretical physics and deep learning.
    - [Physics-based Deep Learning](https://physicsbaseddeeplearning.org/intro.html) ([Paper](https://arxiv.org/abs/2109.05237))
    - [Why can’t I go faster than the speed of light? (2009)](https://gravityandlevity.wordpress.com/2009/04/08/why-cant-i-go-faster-than-the-speed-of-light-hints-from-electrodynamics/) ([HN](https://news.ycombinator.com/item?id=28502084))
    - [How can electrons be “topological”? (2020)](https://gravityandlevity.wordpress.com/2020/07/14/how-can-electrons-be-topological/)
    - [Scientists Create Matter From Pure Light, Proving the Breit-Wheeler Effect (2021)](https://science-news.co/scientists-create-matter-from-pure-light-proving-the-breit-wheeler-effect/) ([Reddit](https://www.reddit.com/r/Physics/comments/pnqvwd/scientists_create_matter_from_pure_light_proving/)) ([HN](https://news.ycombinator.com/item?id=28521970))
    - [Physics for Engineers and Scientists Book (2003)](https://www.goodreads.com/book/show/789047.Physics_for_Scientists_and_Engineers)
    - [UC Berkeley: PHYS 10 - Physics for Future Presidents (2017)](https://www.youtube.com/playlist?list=PLaLOVNqqD-2Ep5N9os9jWMSkxK_TLki9h)
    - [New to Physics resources (2021)](https://www.reddit.com/r/Physics/comments/pv2i02/new_to_physics/)
    - [What a solid made of electrons looks like (2021)](https://www.nature.com/articles/d41586-021-02657-6) ([HN](https://news.ycombinator.com/item?id=28720506))
    - [What hidden symmetry is controlling the Universe? (2021)](https://overcast.fm/+Oq0arDngg)
    - [The Nobel Prize in Physics 2021- Physics for climate and other complex phenomena](https://www.nobelprize.org/prizes/physics/2021/press-release/) ([HN](https://news.ycombinator.com/item?id=28757304)) ([Reddit](https://www.reddit.com/r/Physics/comments/q1t338/the_nobel_prize_in_physics_2021/)) ([Tweet](https://twitter.com/C4COMPUTATION/status/1445600154799656971))
    - [Atomic resolution video of salt crystals forming in real time (2021)](https://phys.org/news/2021-01-first-ever-atomic-resolution-video-salt.html) ([HN](https://news.ycombinator.com/item?id=28785602))
    - [Five Things We Still Don’t Know About Water (2015)](https://nautil.us/issue/25/water/five-things-we-still-dont-know-about-water) ([HN](https://news.ycombinator.com/item?id=28921543))
    - [Nature Physics](https://www.nature.com/nphys/) ([Twitter](https://twitter.com/NaturePhysics))
    - [MIT Introduction to Special Relativity (2021)](https://ocw.mit.edu/courses/physics/8-20-introduction-to-special-relativity-january-iap-2021/index.htm)
    - [What does it mean for light to be a wave? (2021)](https://www.reddit.com/r/quantum/comments/qsrbi1/what_does_it_mean_for_light_to_be_a_wave/)
    - [Invariant Tensors in Gauge Theories (2018)](https://arxiv.org/abs/1806.04332) ([Tweet](https://twitter.com/SamuelGWalters/status/1459828154546065411))
    - [Five mysteries the Standard Model can’t explain (2021)](https://www.symmetrymagazine.org/article/five-mysteries-the-standard-model-cant-explain) ([HN](https://news.ycombinator.com/item?id=29264091))
    - [Symmetry Magazine](https://www.symmetrymagazine.org/) - Dimensions of particle physics.
    - [Ultracold, superdense atoms become invisible (2021)](https://news.mit.edu/2021/atoms-ultracold-scatter-light-1118) ([HN](https://news.ycombinator.com/item?id=29280780))
    - [Into the Cool: Energy Flow, Thermodynamics, and Life by Eric D. Schneider (2006)](https://www.goodreads.com/book/show/52737.Into_the_Cool)
    - [Gauss Linking Number and Electro-magnetic Uncertainty Principle (1997)](https://arxiv.org/abs/hep-th/9701136) ([Tweet](https://twitter.com/johncarlosbaez/status/1462152095658876929))
    - [Something Interesting about Albert Einstein’s Ph.D. Thesis](https://www.cantorsparadise.com/something-interesting-about-albert-einsteins-ph-d-thesis-a7bf1869059e)
    - [Gravitation without the equivalence principle (2003)](https://arxiv.org/abs/gr-qc/0304106)
    - [Gravitation without the equivalence principle (1957)](http://www.fuchs-braun.com/media/8a5e157dba163e00ffff8016ffffffef.pdf)
    - [Solver-in-the-Loop: Learning from Differentiable Physics to Interact with Iterative PDE-Solvers (2020)](https://arxiv.org/abs/2007.00016) ([Code](https://github.com/tum-pbs/Solver-in-the-Loop))
    - [What Impossible Meant to Richard Feynman (2021)](https://nautil.us/issue/108/change/what-impossible-meant-to-richard-feynman) ([HN](https://news.ycombinator.com/item?id=29392021))
    - [The Mystery of Snowflakes (2021)](https://www.youtube.com/watch?v=ao2Jfm35XeE)
    - [Gravitational waves should permanently distort space-time (2021)](https://www.quantamagazine.org/gravitational-waves-should-permanently-distort-space-time-20211208/) ([HN](https://news.ycombinator.com/item?id=29485803))
    - [Oxford Physics Interview (2021)](https://www.youtube.com/watch?v=_A65Xdo6Wog)
    - [We all move at the Speed of Light (2018)](https://www.youtube.com/watch?v=au0QJYISe4c) ([Reddit](https://www.reddit.com/r/RationalPsychonaut/comments/rfe3e5/dmt_timelessness_and_traveling_at_the_speed_of/hohp3z6/?context=3))
    - [The Year in Physics (2021)](https://www.quantamagazine.org/the-year-in-physics-20211222/) ([Video](https://www.youtube.com/watch?v=FMM7GWnAv0A))
    - [The Origins Of Constants Of Motion (2019)](https://tilman.dev/blog/2019/03/the-origins-of-constants-of-motion-working-title)
    - [A delightful quirk of relativity theory (2022)](https://twitter.com/MarkusDeserno/status/1482811504424542211) ([HN](https://news.ycombinator.com/item?id=29977041))
    - [The Joule-Thomson Effect and The Models We Know (2021)](https://mattferraro.dev/posts/joule-thomson)
    - [New lightweight material is stronger than steel (2022)](https://news.mit.edu/2022/polymer-lightweight-material-2d-0202) ([HN](https://news.ycombinator.com/item?id=30180839))
    - [Protons are probably smaller than long thought (2022)](https://www.uni-bonn.de/en/news/020-2022) ([HN](https://news.ycombinator.com/item?id=30210999))
    - [PDEs you should know](https://www.lucaspauker.com/pdes) ([HN](https://news.ycombinator.com/item?id=30263330))
    - [How Einstein arrived at his theory of general relativity](https://lithub.com/how-einstein-arrived-at-his-theory-of-general-relativity/) ([HN](https://news.ycombinator.com/item?id=30306190))
    - [Why do electrons and protons have charge of exactly the same magnitude? (2022)](https://www.reddit.com/r/AskPhysics/comments/st6zj3/why_do_electrons_and_protons_have_charge_of/)
    - [What actually are electromagnetic waves? (2022)](https://www.reddit.com/r/AskPhysics/comments/stvvw7/what_actually_are_electromagnetic_waves/)
    - [Главная надежда теоретической физики 21 века: Суперсимметрия (2022)](https://www.youtube.com/watch?v=CMusg2Mqsg4)
    - [Resources to self learn physics (2022)](https://www.reddit.com/r/AskPhysics/comments/sxrg4q/how_can_i_learn_physics_on_my_own/)
    - [A deepening crisis forces physicists to rethink the structure of nature’s laws (2022)](https://www.quantamagazine.org/crisis-in-particle-physics-forces-a-rethink-of-what-is-natural-20220301/) ([HN](https://news.ycombinator.com/item?id=30516078))
    - [What is the most surprising thing we don't know (in physics)? (2022)](https://www.reddit.com/r/AskPhysics/comments/tcqe39/what_is_the_most_surprising_thing_we_dont_know_in/)
    - [Negative Temperature](https://en.wikipedia.org/wiki/Negative_temperature) ([HN](https://news.ycombinator.com/item?id=30666352))
    - [Nonlinear Dynamics: Concise Introduction Interlaced with Code (2022)](https://link.springer.com/book/10.1007/978-3-030-91032-7) ([Code](https://github.com/JuliaDynamics/NonlinearDynamicsTextbook))
    - [Misconceptions that are common among physics students (2022)](https://www.reddit.com/r/AskPhysics/comments/tmm1xz/what_are_some_misconceptions_that_are_common/)
    - [ELI5: Why is a Planck’s length the smallest possible distance?](https://www.reddit.com/r/explainlikeimfive/comments/tsompf/eli5_why_is_a_plancks_length_the_smallest/)
    - [What I learned as a hired consultant to autodidact physicists (2016)](https://aeon.co/ideas/what-i-learned-as-a-hired-consultant-for-autodidact-physicists) ([HN](https://news.ycombinator.com/item?id=30908084))
    - [Twenty-five years of nanoscale thermodynamics (2022)](https://www.nature.com/articles/d41586-022-00869-y) ([Tweet](https://twitter.com/seanmcarroll/status/1511797026224173059))
    - [W boson mass may be 0.1% larger than predicted by the standard model (2022)](https://www.quantamagazine.org/fermilab-says-particle-is-heavy-enough-to-break-the-standard-model-20220407/) ([Reddit](https://www.reddit.com/r/Physics/comments/tyjgsu/w_boson_mass_may_be_01_larger_than_predicted_by/)) ([HN](https://news.ycombinator.com/item?id=30955033))
    - [Ludwig Boltzmann's inventions](https://twitter.com/MarkusDeserno/status/1512822212646125569)
    - [Faster-than-light communication - Wikipedia](https://en.wikipedia.org/wiki/Faster-than-light_communication)
    - [Collection of Database and Dataset Resources in Materials Science](https://github.com/sedaoturak/data-resources-for-materials-science)
    - [Lectures on Faster-than-Light Travel and Time Travel (2019)](https://arxiv.org/abs/1907.04178) ([HN](https://news.ycombinator.com/item?id=31156276))
    - [It took me 10 years to understand entropy (2022)](https://www.cantorsparadise.com/it-took-me-10-years-to-understand-entropy-here-is-what-i-learned-b2d51e8ccd4c) ([HN](https://news.ycombinator.com/item?id=31164725))
    - [Did the W-boson just “break the standard model”? (2022)](http://backreaction.blogspot.com/2022/04/did-w-boson-just-break-standard-model.html) ([HN](https://news.ycombinator.com/item?id=31215891))
    - [Nice resource for getting up to speed on physics (2022)](https://www.reddit.com/r/AskPhysics/comments/uhf6cb/i_dropped_physics_in_high_school_im_now_super/)
    - [Supersymmetry, explained visually (2022)](https://www.youtube.com/watch?v=0GUTJQCeKBE) ([Reddit](https://www.reddit.com/r/Physics/comments/uq5tpn/supersymmetry_explained_visually/))
    - [A mind-blowing explanation of symmetry | Frank Wilczek (2022)](https://www.youtube.com/watch?v=sMg4XJG2XyY)
    - [The information-theoretic foundation of thermodynamic work extraction (2022)](https://iopscience.iop.org/article/10.1088/2399-6528/ac70a7) ([Tweet](https://twitter.com/DavidDeutschOxf/status/1530199266286882816))
    - [Ask HN: How to do self-study on Physics (2022)](https://news.ycombinator.com/item?id=31549032)
    - [The Electromagnetic Spectrum](https://twitter.com/WorldAndScience/status/1529717989326696449) - All the parts of the electromagnetic spectrum are the same thing—radiation. Radiation is made up of a stream of photons—particles without mass that move in a wave pattern all at the same speed, the speed of light.
    - [Jupyter notebook with steps to rediscover the Higgs boson yourself](https://github.com/meevans1/How-to-rediscover-the-Higgs)
    - [James Clerk Maxwell - A Sense of Wonder - Documentary](https://www.youtube.com/watch?v=ANIkxDm8bF4)
    - [Please, don't build another Large Hadron Collider (2022)](https://bigthink.com/hard-science/large-hadron-collider-economics/) ([HN](https://news.ycombinator.com/item?id=31651086))
    - [Lithium - Periodic Table of Videos (2016)](https://www.youtube.com/watch?v=LfS10ArXTBA)
    - [preCICE](https://github.com/precice/precice) - Coupling library for partitioned multi-physics simulations, including, but not restricted to fluid-structure interaction and conjugate heat transfer simulations. ([Web](https://precice.org/))
    - [Ask HN: What is a nature of a magnetic field](https://news.ycombinator.com/item?id=31968099)
    - [What would change if the speed of light was not constant in all reference frames](https://www.reddit.com/r/AskPhysics/comments/vtcrrn/what_would_change_if_the_speed_of_light_was_not/)
    - [Physicists discover a “family” of robust, superconducting graphene structures (2022)](https://news.mit.edu/2022/superconducting-graphene-family-0708) ([HN](https://news.ycombinator.com/item?id=32036523))
    - [Deep Learning for Physics Research](https://deeplearningforphysicsresearchbook.github.io/deep-learning-physics/) ([Code](https://github.com/DeepLearningForPhysicsResearchBook/deep-learning-physics))
    - [What is the holy grail in you field or area of research? (2022)](https://www.reddit.com/r/Physics/comments/wcttde/what_is_the_holy_grail_in_you_field_or_area_of/)
    - [Iris](https://github.com/LaurentRDC/iris-ued) - Ultrafast electron scattering data exploration.
    - [Experimental protocol for testing the mass–energy–information equivalence principle (2022)](https://aip.scitation.org/doi/10.1063/5.0087175)
    - [The strength of the strong force (2022)](https://phys.org/news/2022-08-strength-strong.html) ([HN](https://news.ycombinator.com/item?id=32409102))
    - [Awesome Photonics](https://github.com/joamatab/awesome_photonics)
    - [The origin of the strong form of superconductivity (2022)](https://www.quantamagazine.org/high-temperature-superconductivity-understood-at-last-20220921/) ([HN](https://news.ycombinator.com/item?id=32937828))
    - [Why do mirrors flip left and right but not up and down?](https://www.youtube.com/watch?v=o_D-HsMOYQ8) ([Tweet](https://twitter.com/thinkagainer/status/1573715621388369922))
    - [Algorithmic Differentiation for Automatized Modelling of Machine Learned Force Fields (2022)](https://arxiv.org/abs/2208.12104) ([Code](https://github.com/niklasschmitz/ad-kernels))
    - [List of physics YouTube channels (2022)](https://www.reddit.com/r/Physics/comments/y6uzbx/i_made_a_list_of_physics_youtube_channels/)
    - [Sound (2022)](https://ciechanow.ski/sound/) ([HN](https://news.ycombinator.com/item?id=33249215))
    - [Inside the Proton (2022)](https://www.quantamagazine.org/inside-the-proton-the-most-complicated-thing-imaginable-20221019/) ([HN](https://news.ycombinator.com/item?id=33262637))
    - [Protons and Charm Quarks: A Lesson From Virtual Particles (2022)](https://profmattstrassler.com/2022/09/09/protons-and-charm-quarks-a-lesson-from-virtual-particles/)
    - [Why is symmetry so important in particle physics? (2022)](https://mfaizan.github.io/2022/10/02/symmetry.html) ([HN](https://news.ycombinator.com/item?id=33400726))
    - [Modern day physicists are likely going to be in the history books 50 or 100 years from now (2022)](https://www.reddit.com/r/Physics/comments/yhvgow/what_modern_day_physicists_are_likely_going_to_be/)
    - [Behavior of spin glasses (2022)](https://phys.org/news/2022-11-mathematics-dont-behavior-glasses.html) ([HN](https://news.ycombinator.com/item?id=33573555))
    - [How to Think About Relativity’s Concept of Space-Time (2022)](https://www.quantamagazine.org/how-to-think-about-relativitys-concept-of-space-time-20221114/)
    - [MadMiner: Machine learning-based inference for particle physics (2020)](https://arxiv.org/abs/1907.10621) ([Code](https://github.com/madminer-tool/madminer))
    - [Is there a good book for learning intro to electricity and magnetism? (2022)](https://www.reddit.com/r/Physics/comments/z361db/is_there_a_good_book_for_learning_intro_to/)
    - [Packmol](https://github.com/m3g/packmol) - Creates Initial Configurations for Molecular Dynamics Simulations.
    - [Mysteries of Fundamental Physics (2022)](https://www.youtube.com/watch?v=pyP59YPtiIo)
    - [Great Physicists: Paul A.M. Dirac - The Taciturn Genius (2020)](https://www.youtube.com/watch?v=aswWUQQxDhU)
    - [Great Physicists: Niels Bohr, the Father of Atomic Physics (2020)](https://www.youtube.com/watch?v=vEFCXoITrLA)
    - [Why Space and Time Are an Illusion - The Mathematical Reality (2020)](https://www.youtube.com/watch?v=zxAV_Re4OWA)
    - [Awesome Physics](https://github.com/wbierbower/awesome-physics)
    - [Great Physicists: Ernst Mach, the man who understood gravity (2022)](https://www.youtube.com/watch?v=V_GYOdQfn44)
    - [Unsolved Mysteries: Spin - and a Tentative Explanation](https://www.youtube.com/watch?v=yEJicBTTabE)
    - [Are Maxwell's Equations Correct? - Variable Speed of Light (2022)](https://www.youtube.com/watch?v=GYA31AKZfbs)
    - [Ten Minute Physics](https://matthias-research.github.io/pages/tenMinutePhysics/index.html) ([HN](https://news.ycombinator.com/item?id=33925047))
    - [Unsolved Mysteries: Beta Decay and the Struggle Between Pauli and Bohr](https://www.youtube.com/watch?v=9ukdBHFRjpM)
    - [Misleading Concepts: The Planck Length](https://www.youtube.com/watch?v=IEp3QdqSE0s)
    - [Let's talk Pseudoscience](https://www.reddit.com/r/Physics/comments/h7qblq/lets_talk_pseudoscience/)
    - [Large Hadron Collider Beauty releases first set of data to the public (2022)](https://home.cern/news/news/knowledge-sharing/lhcb-releases-first-set-data-public)
    - [Electromagnetic wave simulation](https://cemsim.com/) ([Code](https://github.com/RobinKa/maxwell-simulation))
    - [Irrelevant Topics In Physics](https://github.com/thoppe/Presentation_Irrelevant_Topics_In_Physics)
    - [ViSNet: a scalable and accurate geometric deep learning potential for molecular dynamics simulation (2022)](https://arxiv.org/abs/2210.16518) ([Code](https://github.com/microsoft/ViSNet))
    - [Weaving paper strips for designing of general curved surface with geometrical elasticity (2022)](https://arxiv.org/abs/2211.06372) ([Code](https://github.com/hyrodium/ElasticSurfaceEmbedding.jl))
    - [Particle Lenia and the energy-based formulation (2022)](https://google-research.github.io/self-organising-systems/particle-lenia/) ([HN](https://news.ycombinator.com/item?id=34108724))
    - [Picture This: The Periodic Table](https://pioneerworks.org/broadcast/picture-this-periodic-table)
    - [How Many States Of Matter Are There? (2022)](https://www.youtube.com/watch?v=184eP_KuXek)
    - [Arvin Ash - YouTube](https://www.youtube.com/@ArvinAsh/videos)
    - [The Equation That Explains (Nearly) Everything! (2023)](https://www.youtube.com/watch?v=PHiyQID7SBs)
    - [Why Is Everything Made Of Atoms? (2022)](https://www.youtube.com/watch?v=ae36scLdCsE)
    - [Diamond formation from hydrocarbon mixtures in planets (2022)](https://arxiv.org/abs/2207.02927) ([Code](https://github.com/BingqingCheng/highp-ch))
    - [A 50-Year Quest: My Personal Journey with the Second Law of Thermodynamics (2023)](https://writings.stephenwolfram.com/2023/02/a-50-year-quest-my-personal-journey-with-the-second-law-of-thermodynamics/) ([HN](https://news.ycombinator.com/item?id=34634969))
    - [What's Going Wrong in Particle Physics? (2023)](https://www.youtube.com/watch?v=lu4mH3Hmw2o) ([HN](https://news.ycombinator.com/item?id=34772049))
    - [How Does The Nucleus Hold Together? (2023)](https://www.youtube.com/watch?v=E8hyodMhbRw)
    - [Modern view on constants in fundamental physics (2023)](https://twitter.com/martinmbauer/status/1627221248160792578)
    - [What the Higgs boson tells us about the universe (2023)](https://www.symmetrymagazine.org/article/what-the-higgs-boson-tells-us-about-the-universe)
    - [Evidence for Dirac flat band superconductivity enabled by quantum geometry (2023)](https://www.nature.com/articles/s41586-022-05576-2) ([HN](https://news.ycombinator.com/item?id=34891407))
    - [Double-slit time diffraction at optical frequencies (2023)](https://www.nature.com/articles/s41567-023-01993-w) ([HN](https://news.ycombinator.com/item?id=35433982))
    - [Why gravity is not like the other forces (2023)](https://www.quantamagazine.org/why-gravity-is-not-like-the-other-forces-20200615/) ([HN](https://news.ycombinator.com/item?id=35722206))
    - [What exactly is the Planck length?](https://twitter.com/WKCosmo/status/1651986002490138626)
    - [Road to Reality Essays](https://reality.mentat.org/) - Journey through computational physics, from eval/apply to the Einstein field equations. ([Code](https://github.com/mentat-collective/road-to-reality))
    - [Periodicum](https://periodicum.netlify.app/) - Simple and interactive periodic table. ([Code](https://github.com/KaeserOfHonour/Periodicum))
    - [Neil Gershenfeld: Self-Replicating Robots and the Future of Fabrication (2023)](https://www.youtube.com/watch?v=YDjOS0VHEr4)
    `,
  })
})

async function main() {
  serve(app)
    .listen(3000)
    .once("listening", () => {
      console.log("🚀 Server started on port 3000")
    })
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
