// GENERATED by @edgedb/generate v0.3.0
// Run 'npx @edgedb/generate edgeql-js' to re-generate

export * as edgedb from "edgedb";
export { spec } from "./__spec__";
export * as syntax from "./syntax";
export * as castMaps from "./castMaps";
