// GENERATED by @edgedb/generate v0.3.4

import type {Executor} from "edgedb";

export type GetGlobalTopicArgs = {
  "topicName": string;
  "email": string;
};

export type GetGlobalTopicReturns = {
  "learningStatus": string;
  "likedLinks": {
    "id": string;
    "url": string;
  }[];
} | null;

export async function getGlobalTopic(client: Executor, args: GetGlobalTopicArgs): Promise<GetGlobalTopicReturns> {
  return client.querySingle(`\
with topicName := <str>$topicName,
     email := <str>$email
select User {
  learningStatus := "to_learn" if topicName in .topicsToLearn.name
  else "learning" if topicName in .topicsLearning.name
  else "learned" if topicName in .topicsLearned.name
  else "none",
  likedLinks: { id, url } filter .mainTopic.name = topicName
}
filter .email = email`, args);

}
