// GENERATED by @edgedb/generate v0.3.4

import type {Executor} from "edgedb";

export type QueryGetGlobalTopicArgs = {
  "topicName": string;
  "hankoId": string;
};

export type QueryGetGlobalTopicReturns = {
  "learningStatus": string;
  "likedLinks": {
    "id": string;
    "url": string;
  }[];
} | null;

export async function queryGetGlobalTopic(client: Executor, args: QueryGetGlobalTopicArgs): Promise<QueryGetGlobalTopicReturns> {
  return client.querySingle(`\
with topicName := <str>$topicName,
     hankoId := <str>$hankoId
select User {
  learningStatus := "to_learn" if topicName in .topicsToLearn.name
  else "learning" if topicName in .topicsLearning.name
  else "learned" if topicName in .topicsLearned.name
  else "none",
  likedLinks: { id, url } filter .mainTopic.name = topicName
}
filter .hankoId = hankoId`, args);

}
