// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type QueryGetLearningStatusArgs = {
  "topicName": string;
  "hankoId": string;
};

export type QueryGetLearningStatusReturns = {
  "learningStatus": string;
} | null;

export async function queryGetLearningStatus(client: Executor, args: QueryGetLearningStatusArgs): Promise<QueryGetLearningStatusReturns> {
  return client.querySingle(`\
with topicName := <str>$topicName,
     hankoId := <str>$hankoId
select User {
  learningStatus := "to_learn" if topicName in .topicsToLearn.name
  else "learning" if topicName in .topicsLearning.name
  else "learned" if topicName in .topicsLearned.name
  else "none"
}
filter .hankoId = hankoId`, args);

}
