// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type QueryGetGlobalTopicArgs = {
  "topicName": string;
  "hankoId": string;
};

export type QueryGetGlobalTopicReturns = {
  "learningStatus": string;
  "likedLinkIds": string[];
  "completedLinkIds": string[];
} | null;

export async function queryGetGlobalTopic(client: Executor, args: QueryGetGlobalTopicArgs): Promise<QueryGetGlobalTopicReturns> {
  return client.querySingle(`\
with topicName := <str>$topicName,
     hankoId := <str>$hankoId
select User {
  learningStatus := "to_learn" if topicName in .topicsToLearn.name
  else "learning" if topicName in .topicsLearning.name
  else "learned" if topicName in .topicsLearned.name
  else "none",
  likedLinkIds := (
  select User.likedLinks
  filter .mainTopic.name = topicName
  ).id,
  completedLinkIds := (
  select User.completedLinks
  filter .mainTopic.name = topicName
  ).id
}
filter .hankoId = hankoId`, args);

}
