/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksImport } from './routes/tasks'
import { Route as DailyImport } from './routes/daily'
import { Route as AllNotesImport } from './routes/all-notes'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as DailyDateImport } from './routes/daily.$date'

// Create/Update Routes

const TasksRoute = TasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const DailyRoute = DailyImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRoute,
} as any)

const AllNotesRoute = AllNotesImport.update({
  id: '/all-notes',
  path: '/all-notes',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DailyDateRoute = DailyDateImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => DailyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/all-notes': {
      id: '/all-notes'
      path: '/all-notes'
      fullPath: '/all-notes'
      preLoaderRoute: typeof AllNotesImport
      parentRoute: typeof rootRoute
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/daily/$date': {
      id: '/daily/$date'
      path: '/$date'
      fullPath: '/daily/$date'
      preLoaderRoute: typeof DailyDateImport
      parentRoute: typeof DailyImport
    }
  }
}

// Create and export the route tree

interface DailyRouteChildren {
  DailyDateRoute: typeof DailyDateRoute
}

const DailyRouteChildren: DailyRouteChildren = {
  DailyDateRoute: DailyDateRoute,
}

const DailyRouteWithChildren = DailyRoute._addFileChildren(DailyRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRoute
  '/all-notes': typeof AllNotesRoute
  '/daily': typeof DailyRouteWithChildren
  '/tasks': typeof TasksRoute
  '/daily/$date': typeof DailyDateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRoute
  '/all-notes': typeof AllNotesRoute
  '/daily': typeof DailyRouteWithChildren
  '/tasks': typeof TasksRoute
  '/daily/$date': typeof DailyDateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRoute
  '/all-notes': typeof AllNotesRoute
  '/daily': typeof DailyRouteWithChildren
  '/tasks': typeof TasksRoute
  '/daily/$date': typeof DailyDateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/all-notes' | '/daily' | '/tasks' | '/daily/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/all-notes' | '/daily' | '/tasks' | '/daily/$date'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/all-notes'
    | '/daily'
    | '/tasks'
    | '/daily/$date'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AllNotesRoute: typeof AllNotesRoute
  DailyRoute: typeof DailyRouteWithChildren
  TasksRoute: typeof TasksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AllNotesRoute: AllNotesRoute,
  DailyRoute: DailyRouteWithChildren,
  TasksRoute: TasksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/all-notes",
        "/daily",
        "/tasks"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx"
    },
    "/all-notes": {
      "filePath": "all-notes.tsx"
    },
    "/daily": {
      "filePath": "daily.tsx",
      "children": [
        "/daily/$date"
      ]
    },
    "/tasks": {
      "filePath": "tasks.tsx"
    },
    "/daily/$date": {
      "filePath": "daily.$date.tsx",
      "parent": "/daily"
    }
  }
}
ROUTE_MANIFEST_END */
