type Inline0 {
	name: String!
	prettyName: String!
	connections: [String!]!
}
type Inline1 {
	latestGlobalTopicGraph: [Inline0!]!
}
type Inline2 {
	username: String!
	links: [Link!]
}
type Inline3 {
	public: Inline1
	auth: Inline2
}
enum LearningStatus {
	Learn
	Learning
	Learned
}
type Link {
	title: String!
	url: String!
}
type Mutation {
	createUser(email: String!): Boolean!
	updatePersonalLink(linkId: String!, status: LearningStatus!): Boolean!
}
type Query {
	webIndex: Inline3!
}
schema {
	query: Query
	mutation: Mutation
}
