type Inline0 {
	name: String!
	prettyName: String!
	connections: [String!]!
}
type Inline1 {
	latestGlobalTopicGraph: [Inline0!]!
}
type Inline2 {
	title: String!
	pageUrl: String!
}
type Inline3 {
	links: [Link!]!
	bio: String
	personalPages: [Inline2!]!
	username: String
}
type Inline4 {
	public: Inline1
	auth: Inline3
}
type Inline5 {
	id: String
	url: String
	title: String
	description: String
	year: Int
	note: String
}
type Inline6 {
	personalLinks: [Inline5!]!
}
enum LearningStatus {
	Learn
	Learning
	Learned
}
type Link {
	title: String
	url: String
	description: String
	note: String
}
type Mutation {
	createUser(email: String!): Boolean!
	updateUserBio(bio: String!): Boolean!
	updatePersonalLink(linkId: String!, status: LearningStatus!): Boolean!
}
type Query {
	webIndex: Inline4!
	mobileIndex: Inline6!
}
schema {
	query: Query
	mutation: Mutation
}
