type Inline0 {
	filterStatus: String!
}
type Inline1 {
	auth: Inline0
}
enum LearningStatus {
	Learn
	Learning
	Learned
}
type Mutation {
	createUser(email: String!): Boolean!
	updatePersonalLink(linkId: String!, status: LearningStatus!): Boolean!
}
type Query {
	mobileIndex: Inline1!
}
schema {
	query: Query
	mutation: Mutation
}
